### PR TITLE
htmlproof is now htmlproofer

### PR DESCRIPTION
**Pull request by winstliu**
In addition, `sudo: true` because that's what the Travis docs recommend for Trusty.

Will merge once build passes as this does not affect the site itself.

### CODE REVIEW

**Comment by winstliu** [comment]
@threedot14 for image failures related to `https://cdn.mhsengineering.club`.

**Comment by three** [comment]
Both images are working fine for me. Maybe Cloudflare is blocking Travis? I'll look into it.

**Comment by winstliu** [comment]
Yeah, they were for me as well.  Of note is that the favicon error is only being triggered on one page while the rest are fine.

**Comment by three** [comment]
Cloudflare asks certain hosts for a Captcha and I can't control it. Whitelisting Travis CI might work but they don't publish their IPs publicly. It would help if I could see the full request, like what headers Cloudflare is sending back. Maybe we can just disable external checks?

**Comment by winstliu** [comment]
Yeah, I can definitely disable image checks.

**Pull request closed without merging**
