### PR TITLE
Massive styles refactoring

### LINKED ISSUE #2: Fix Formatting
From Ms. Kolker:
> [please fix] formatting on home page - make picture smaller so that visitors can see that there is text below.  and reduce font on text so it fits inside the boxes

### PR DESCRIPTION
**Pull request by winstliu**
Refactor all the things.

Closes #2.

### CODE REVIEW

**Comment by winstliu** [comment]
At this point everything is coming along nicely.  The biggest problem remaining is the `.infobox` class.  It was initially geared specifically towards the homepage Q&A section, but the contact and FAQ pages are also using it, and there's no (easy) way to make it adapt to all three use-cases; it's already way too generic and canceling out font-related attributes.  I plan to separate it into different components (see `.enclosed-box` for an example) so that each section can only use what it needs to.

With that in mind, here's what I noticed that still needs fixing before this PR can be considered for merging:
- [x] Q&A boxes on the homepage are misaligned; the first one is "taller" than the other two
- [x] Poiret One font for `h2` question tags on the home and Contact pages are being overridden by `.infobox` and defaulting to Helvetica instead
- [x] The News page is styled differently than all the other pages (it's using black Poiret One for plain text and doesn't have a background)

**Comment by winstliu** [comment]
Only thing left is the Q&A boxes now.

**Comment by winstliu** [comment]
Ready for review! :rocket:

**Comment by three** [comment]
While we're restyling, it might be a good idea to make `link` tags consistent. Some pages have `href` before `rel` while others have `rel` before `href`.

**Comment by winstliu** [comment]
@threedot14 fixed!

**Comment by three** [comment]
Looks good. Merging now.

**Pull request merged**
